/**
 * Command IDs for AI Command Center extension.
 * Must match commands defined in package.json contributes.commands.
 */
export const COMMAND_IDS = {
    CREATE_EPIC: 'aicc.createEpic',
    CREATE_STORY: 'aicc.createStory',
    CREATE_TASK: 'aicc.createTask',
    OPEN_PLANNING_PANEL: 'aicc.openPlanningPanel',
    EXPORT_TO_JIRA: 'aicc.exportToJira',
    // Planning tree view context menu commands
    PLANNING_REFRESH: 'aicc.planning.refresh',
    PLANNING_EDIT: 'aicc.planning.edit',
    PLANNING_DELETE: 'aicc.planning.delete',
    PLANNING_COPY_ID: 'aicc.planning.copyId',
    PLANNING_COPY_MARKDOWN: 'aicc.planning.copyAsMarkdown',
    PLANNING_SET_STATUS_NOT_STARTED: 'aicc.planning.setStatusNotStarted',
    PLANNING_SET_STATUS_IN_PROGRESS: 'aicc.planning.setStatusInProgress',
    PLANNING_SET_STATUS_DONE: 'aicc.planning.setStatusDone',
    // MCP commands
    MCP_START: 'aicc.mcp.start',
    MCP_STOP: 'aicc.mcp.stop',
    MCP_RESTART: 'aicc.mcp.restart',
    MCP_GENERATE_SSL: 'aicc.mcp.generateSSL',
    MCP_EXPORT_CONFIG: 'aicc.mcp.exportConfig',
    INIT_EXECUTE: 'aicc.init.execute',
    INIT_CREATE_EXAMPLE: 'aicc.init.createExample',
    INIT_VALIDATE: 'aicc.init.validate',
    INIT_UNDO: 'aicc.init.undo',
    INIT_SHOW_LOG: 'aicc.init.showLog',
    FILE_PROTECTION_SHOW_LOGS: 'aicc.fileProtection.showLogs',
    FILE_PROTECTION_LIST_BACKUPS: 'aicc.fileProtection.listBackups',
    FILE_PROTECTION_RESTORE_BACKUP: 'aicc.fileProtection.restoreBackup',
    FILE_PROTECTION_CONFIGURE: 'aicc.fileProtection.configure',
    UNDO_SHOW_HISTORY: 'aicc.undo.showHistory',
    UNDO_LAST: 'aicc.undo.last',
    UNDO_PANEL: 'aicc.undo.panel',
    UNDO_SINCE: 'aicc.undo.since',
    MERMAID_PREVIEW: 'aicc.mermaid.preview',
    MERMAID_PREVIEW_SELECTION: 'aicc.mermaid.previewSelection',
    CONVERT_PLANTUML: 'aicc.convertPlantUML',
    CONVERT_PLANTUML_SELECTION: 'aicc.convertPlantUMLSelection',
    PLANNING_USE_TEMPLATE: 'aicc.planning.useTemplate',
    PLANNING_LIST_TEMPLATES: 'aicc.planning.listTemplates',
    SEARCH_GLOBAL: 'aicc.search.global',
    SEARCH_BY_TYPE: 'aicc.search.byType',
    // Asset Tree Map commands
    ASSET_TREE_MAP: 'aicc.generateAssetTreeMap',
    ASSET_STATS: 'aicc.showAssetStats',
    ASSET_EXPORT_JSON: 'aicc.exportAssetTreeJson',
    // Synthetic Test commands
    RUN_SYNTHETIC_TESTS: 'aicc.runSyntheticTests',
    QUICK_HEALTH_CHECK: 'aicc.quickHealthCheck',
    // Secondary Panel commands
    OPEN_SETTINGS: 'aicc.openSettings',
    SHOW_DEBUG_PANEL: 'aicc.showDebugPanel',
    SHOW_HELP: 'aicc.showHelp',
    SAVE_ALL_CHANGES: 'aicc.saveAllChanges',
    RUN_NEXT_ITEM: 'aicc.runNextItem',
    UPDATE_ITEM_STATUS: 'aicc.updateItemStatus',
    RUN_ITEM: 'aicc.runItem',
    EDIT_ITEM: 'aicc.editItem',
    SHOW_ITEM_INFO: 'aicc.showItemInfo',
    SHOW_ITEM_CONNECTIONS: 'aicc.showItemConnections',
    SHOW_ITEM_REPO: 'aicc.showItemRepo',
    SHOW_ITEM_COMMENTS: 'aicc.showItemComments',
    // AI Kit commands
    INSTALL_AI_KIT: 'aicc.installAIKit',
    UNINSTALL_AI_KIT: 'aicc.uninstallAIKit',
    REFRESH_AI_KITS: 'aicc.refreshAIKits',
    // Archival commands
    ARCHIVE_ITEMS: 'aicc.archiveItems',
    // Dashboard commands
    SHOW_VELOCITY_CHART: 'aicc.showVelocityChart',
    SHOW_HEALTH_DASHBOARD: 'aicc.showHealthDashboard',
    SHOW_PROMPT_LEADERBOARD: 'aicc.showPromptLeaderboard',
    SEARCH_KNOWLEDGE_BASE: 'aicc.searchKnowledgeBase',
    SHOW_QUEUE_STATUS: 'aicc.showQueueStatus',
    EXPORT_AGENT_MEMORY: 'aicc.exportAgentMemory',
    CONFLUENCE_PUSH: 'aicc.confluencePush',
    CONFLUENCE_PULL: 'aicc.confluencePull',
} as const;
