#!/usr/bin/env python3
"""
Import RAG JSON data into ChromaDB
Usage: python import-to-chromadb.py <json-file> [--chroma-path <path>]
"""

import argparse
import json
import chromadb
from chromadb.config import Settings
from pathlib import Path

def import_to_chromadb(json_file: str, chroma_path: str = ".rag/chromadb"):
    """Import JSON data into ChromaDB"""
    
    # Load JSON data
    with open(json_file, 'r') as f:
        data = json.load(f)
    
    collection_name = data['collection']
    entries = data['entries']
    
    print(f"📥 Importing {len(entries)} entries into collection: {collection_name}")
    
    # Connect to ChromaDB (embedded, no server required)
    client = chromadb.PersistentClient(
        path=chroma_path,
        settings=Settings()
    )
    
    # Get or create collection
    collection = client.get_or_create_collection(
        name=collection_name,
        metadata={"description": f"RAG collection for {collection_name}"}
    )
    
    # Prepare data for ChromaDB
    ids = [entry['id'] for entry in entries]
    documents = [entry['document'] for entry in entries]
    metadatas = [entry['metadata'] for entry in entries]
    
    # Add to collection (ChromaDB generates embeddings automatically)
    collection.add(
        ids=ids,
        documents=documents,
        metadatas=metadatas
    )
    
    print(f"✅ Successfully imported {len(entries)} entries")
    print(f"   ChromaDB path: {chroma_path}")
    print(f"   Collection: {collection_name}")
    
    # Show sample query
    print("\n💡 Sample query:")
    print(f"""
import chromadb
client = chromadb.PersistentClient(path='{chroma_path}')
collection = client.get_collection('{collection_name}')
results = collection.query(query_texts=['your search query'], n_results=5)
""")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Import RAG JSON data into ChromaDB")
    parser.add_argument("json_file", help="Path to JSON file generated by ailey-tag-n-rag")
    parser.add_argument("--chroma-path", default=".rag/chromadb", help="Path to ChromaDB storage (default: .rag/chromadb)")
    
    args = parser.parse_args()
    
    import_to_chromadb(args.json_file, args.chroma_path)
