import { TreeNodeData } from '../types/tree';

/**
 * Print Service
 * Handles printing and PDF export of planning trees
 */
export class PrintService {
    /**
     * Prepare and trigger browser print dialog
     */
    static print(tree: TreeNodeData[]): void {
        // Expand all nodes for printing
        this.expandAllForPrint();
        
        // Add print header
        this.addPrintHeader();
        
        // Trigger print
        window.print();
        
        // Cleanup after print
        setTimeout(() => {
            this.cleanup();
        }, 100);
    }

    /**
     * Export tree as PDF (using browser print-to-PDF)
     */
    static exportPDF(tree: TreeNodeData[]): void {
        // Same as print - browser will handle PDF conversion
        this.print(tree);
    }

    /**
     * Expand all tree nodes before printing
     */
    private static expandAllForPrint(): void {
        const allNodes = document.querySelectorAll('.tree-node');
        allNodes.forEach(node => {
            node.classList.remove('collapsed');
        });
    }

    /**
     * Add print-specific header with metadata
     */
    private static addPrintHeader(): void {
        // Check if header already exists
        if (document.querySelector('.print-header')) {
            return;
        }

        const header = document.createElement('div');
        header.className = 'print-header';
        header.style.display = 'none'; // Hidden on screen, visible in print CSS
        
        const title = document.createElement('h1');
        title.textContent = 'AI Command Center - Planning Tree';
        
        const metadata = document.createElement('div');
        metadata.className = 'metadata';
        metadata.textContent = `Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`;
        
        header.appendChild(title);
        header.appendChild(metadata);
        
        const container = document.querySelector('.container');
        if (container) {
            container.insertBefore(header, container.firstChild);
        }
    }

    /**
     * Add print-specific footer with summary
     */
    private static addPrintFooter(stats: any): void {
        // Check if footer already exists
        if (document.querySelector('.print-footer')) {
            return;
        }

        const footer = document.createElement('div');
        footer.className = 'print-footer';
        footer.style.display = 'none'; // Hidden on screen, visible in print CSS
        
        footer.innerHTML = `
            <strong>Summary:</strong> 
            ${stats.totalEpics} Epics, 
            ${stats.totalStories} Stories, 
            ${stats.totalTasks} Tasks | 
            ${stats.totalPoints} Story Points | 
            Generated by AI Command Center
        `;
        
        const container = document.querySelector('.container');
        if (container) {
            container.appendChild(footer);
        }
    }

    /**
     * Clean up print-specific elements
     */
    private static cleanup(): void {
        const header = document.querySelector('.print-header');
        const footer = document.querySelector('.print-footer');
        
        if (header) {
            header.remove();
        }
        if (footer) {
            footer.remove();
        }
    }

    /**
     * Get printable HTML content
     * Useful for custom PDF generation
     */
    static getPrintableHTML(tree: TreeNodeData[]): string {
        const container = document.querySelector('.container');
        if (!container) {
            return '';
        }

        // Clone the container
        const clone = container.cloneNode(true) as HTMLElement;

        // Remove non-printable elements
        const elementsToRemove = clone.querySelectorAll('.toolbar, .filter-bar, .settings-bar, .shortcuts-panel, .context-menu, .details-panel');
        elementsToRemove.forEach(el => el.remove());

        // Expand all nodes
        const nodes = clone.querySelectorAll('.tree-node');
        nodes.forEach(node => {
            node.classList.remove('collapsed');
        });

        return clone.innerHTML;
    }
}
